#!/bin/bash
#
# pf-client-ip.sh — preserve real client IPs on the self-hosted Dredd.
#
# THE PROBLEM THIS SOLVES
# Lima forwards ports through a userspace (SSH) proxy: it terminates the inbound
# TCP connection on the macOS host and opens a NEW one to the guest. Every
# request therefore reaches the VM from [::1], Docker rewrites that to the bridge
# gateway, and the access log records one constant address for the entire
# internet. Measured 2026-08-26: a request from 172.16.1.27 logged as 172.18.0.1.
#
# pf's `rdr` is DESTINATION nat only — it rewrites where the packet is going and
# leaves the source alone — so redirecting :80/:443 straight to the guest gets
# the real client address all the way to Caddy, with Lima's proxy out of the
# path entirely.
#
# WHY THE GUEST IP IS RESOLVED AND NOT HARDCODED
# The guest's lima0 address comes from vzNAT DHCP (verified: `dynamic`). Pinning
# 192.168.64.2 into a firewall rule would work until the VM restarted onto a
# different lease, at which point inbound traffic would be redirected into a
# black hole — the service would look up from the host and be unreachable from
# outside, which is a miserable thing to debug. This resolves the address at
# load time, and `reload` re-resolves it.
#
# Usage (ON the Studio, needs sudo):
#   sudo ./pf-client-ip.sh install    # write anchor, wire pf.conf, load, persist
#   sudo ./pf-client-ip.sh reload     # re-resolve the guest IP and reload
#   sudo ./pf-client-ip.sh status     # show rules + current mapping
#   sudo ./pf-client-ip.sh uninstall  # remove rules and the boot job
#
set -euo pipefail

VM_NAME="${VM_NAME:-dredd}"
ANCHOR_NAME="dredd"
ANCHOR_FILE="/etc/pf.anchors/${ANCHOR_NAME}"
PLIST="/Library/LaunchDaemons/io.soteriacyber.dredd.pf.plist"
SELF="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"
# The invoking user's lima lives in their home, not root's. launchd runs this
# as root with NO SUDO_USER, which resolved to /var/root and made the boot job
# fail with "limactl not found" — silently, since nothing reads that log. The
# install bakes the real user into the plist so `reload` works at boot.
REAL_USER="${DREDD_LIMA_USER:-${SUDO_USER:-$(whoami)}}"
REAL_HOME="$(eval echo "~${REAL_USER}")"
LIMACTL="${REAL_HOME}/opt/lima/bin/limactl"

die() { echo "ERROR: $*" >&2; exit 1; }

resolve_guest_ip() {
  [ -x "$LIMACTL" ] || die "limactl not found at $LIMACTL"
  local ip
  ip=$(sudo -u "$REAL_USER" "$LIMACTL" shell "$VM_NAME" -- \
        ip -4 -o addr show lima0 2>/dev/null \
        | awk '{print $4}' | cut -d/ -f1 | tr -d '\r')
  [ -n "$ip" ] || die "could not resolve the guest's lima0 address — is the VM running?"
  echo "$ip"
}

wan_iface() { route -n get default 2>/dev/null | awk '/interface:/{print $2}'; }

write_anchor() {
  local guest="$1" iface="$2"
  cat > "$ANCHOR_FILE" <<EOF
# Generated by selfhost/pf-client-ip.sh — do not edit by hand.
# Redirects inbound web traffic straight to the Dredd VM so the ORIGINAL source
# address survives to the access log. rdr is destination-NAT only.
#   guest: ${guest}    wan: ${iface}    generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
rdr pass on ${iface} inet proto tcp from any to any port 80  -> ${guest} port 80
rdr pass on ${iface} inet proto tcp from any to any port 443 -> ${guest} port 443
EOF
  chmod 644 "$ANCHOR_FILE"
}

wire_pf_conf() {
  # ORDERING IS NOT COSMETIC. pf demands rules in a fixed order — options,
  # normalization, queueing, TRANSLATION, filtering — and rejects the whole file
  # otherwise. Appending `rdr-anchor` to the end of macOS's stock pf.conf puts a
  # translation anchor after `anchor "com.apple/*"`, which is a filter anchor, so
  # `pfctl -f` fails and NOTHING loads. (That is exactly what happened on the
  # first install here: rules written, never active, traffic still logging the
  # Docker gateway.) So the rdr-anchor is inserted immediately after the stock
  # rdr-anchor line, and only `load anchor` goes at the end.
  #
  # No filter anchor is needed: these are `rdr pass` rules, which redirect and
  # pass in one step.
  python3 - "$ANCHOR_NAME" "$ANCHOR_FILE" <<'PYEOF'
import re, sys
name, path = sys.argv[1], sys.argv[2]
conf = "/etc/pf.conf"
lines = open(conf).read().splitlines()
# Drop any previous attempt so re-running repairs rather than duplicates.
lines = [l for l in lines
         if not re.match(rf'^\s*(rdr-)?anchor\s+"{name}"\s*$', l)
         and not re.match(rf'^\s*load anchor\s+"{name}"', l)]
out, placed = [], False
for l in lines:
    out.append(l)
    if not placed and re.match(r'^\s*rdr-anchor\s+"com\.apple/\*"', l):
        out.append(f'rdr-anchor "{name}"')
        placed = True
if not placed:                      # no stock rdr-anchor: put ours before the first filter anchor
    out, placed = [], False
    for l in lines:
        if not placed and re.match(r'^\s*anchor\s+"', l):
            out.append(f'rdr-anchor "{name}"'); placed = True
        out.append(l)
if not placed:
    raise SystemExit("could not find a safe insertion point in /etc/pf.conf")
out.append(f'load anchor "{name}" from "{path}"')
open(conf, "w").write("\n".join(out) + "\n")
PYEOF
}

install_plist() {
  # pf rules do not survive a reboot, and neither does the guest's DHCP lease.
  # Re-run `reload` at boot so the rule is regenerated against whatever address
  # the VM comes up with.
  cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>io.soteriacyber.dredd.pf</string>
  <key>ProgramArguments</key>
  <array><string>/bin/bash</string><string>${SELF}</string><string>reload</string></array>
  <key>EnvironmentVariables</key>
  <dict><key>DREDD_LIMA_USER</key><string>${REAL_USER}</string></dict>
  <key>RunAtLoad</key><true/>
  <key>StandardOutPath</key><string>/var/log/dredd-pf.log</string>
  <key>StandardErrorPath</key><string>/var/log/dredd-pf.log</string>
</dict>
</plist>
EOF
  chmod 644 "$PLIST"
  launchctl bootout system "$PLIST" 2>/dev/null || true
  launchctl bootstrap system "$PLIST" 2>/dev/null || true
}

apply() {
  local guest iface
  guest="$(resolve_guest_ip)"; iface="$(wan_iface)"
  [ -n "$iface" ] || die "no default route interface"
  write_anchor "$guest" "$iface"
  wire_pf_conf
  sysctl -w net.inet.ip.forwarding=1 >/dev/null
  # Do NOT swallow pfctl's exit status. The first version of this script piped
  # it through grep, so a rejected ruleset looked like success and the operator
  # was told "applied" while nothing was loaded.
  local out
  if ! out=$(pfctl -f /etc/pf.conf 2>&1); then
    echo "$out" | grep -vi "^No ALTQ" >&2 || true
    die "pfctl rejected the ruleset — nothing was loaded"
  fi
  echo "$out" | grep -viE "^No ALTQ|^$" >&2 || true
  pfctl -e 2>&1 | grep -vi "already enabled" >&2 || true
  # Prove the rule is actually resident rather than merely written to a file.
  if ! pfctl -a "$ANCHOR_NAME" -s nat 2>/dev/null | grep -q "${guest}"; then
    die "ruleset loaded but the ${ANCHOR_NAME} anchor holds no rule for ${guest}"
  fi
  echo "  applied and VERIFIED resident: ${iface} :80,:443  ->  ${guest}"
}

case "${1:-}" in
  install)
    [ "$(id -u)" -eq 0 ] || die "run with sudo"
    apply; install_plist
    echo "  boot job installed: ${PLIST}"
    echo
    echo "  VERIFY from another machine, then check the log:"
    echo "    curl -s https://hook.soteriacyber.com/health?iptest >/dev/null"
    echo "    # then, on the Studio:"
    echo "    ${LIMACTL} shell ${VM_NAME} -- docker exec dredd-selfhost-caddy-1 \\"
    echo "      sh -c 'grep iptest /data/access-hook.log | tail -1' | grep -o '\"client_ip\":\"[^\"]*\"'"
    echo "  A real address means it worked. 172.18.0.1 means it did not."
    ;;
  reload)
    [ "$(id -u)" -eq 0 ] || die "run with sudo"
    apply ;;
  status)
    [ "$(id -u)" -eq 0 ] || die "run with sudo"
    echo "  pf: $(pfctl -s info 2>/dev/null | head -1)"
    echo "  anchor rules:"; pfctl -a "$ANCHOR_NAME" -s nat 2>/dev/null | sed 's/^/    /'
    echo "  boot job: $(launchctl print system/io.soteriacyber.dredd.pf >/dev/null 2>&1 && echo loaded || echo 'not loaded')"
    ;;
  uninstall)
    [ "$(id -u)" -eq 0 ] || die "run with sudo"
    launchctl bootout system "$PLIST" 2>/dev/null || true
    rm -f "$PLIST" "$ANCHOR_FILE"
    # Leave pf.conf's anchor lines: they are inert without the anchor file, and
    # editing pf.conf in place risks corrupting a file the OS also manages.
    pfctl -a "$ANCHOR_NAME" -F nat 2>/dev/null || true
    echo "  removed. pf.conf anchor lines left in place (inert without the anchor file)."
    ;;
  *) die "usage: sudo $0 {install|reload|status|uninstall}" ;;
esac
