version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 621978938576.dkr.ecr.eu-west-2.amazonaws.com
  build:
    commands:
      - docker build -t judge-ai-dredd-test7 .
      - "docker tag judge-ai-dredd-test7:latest 621978938576.dkr.ecr.eu-west-2.amazonaws.com/judge-ai-dredd-test7:latest"
  post_build:
    commands:
      - "docker push 621978938576.dkr.ecr.eu-west-2.amazonaws.com/judge-ai-dredd-test7:latest"
